import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, BarChart3, Check, ChevronDown, Database, GitBranch, Leaf, PackageOpen, ShieldCheck, Sparkles, Target, Tractor, Users } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { SiteHeader, Brand } from '@/components/site-header';
import fields from '@/assets/sysagro-fields.jpg';

export const Route=createFileRoute('/')({head:()=>({meta:[{title:'Sysagro — Gestión agropecuaria basada en datos'},{name:'description',content:'Software de gestión agropecuaria para trazabilidad, recursos y decisiones estratégicas.'},{property:'og:title',content:'Sysagro — Gestión agropecuaria basada en datos'},{property:'og:description',content:'Transformá los datos de campo en mejores decisiones.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Home});
const pillars=[{icon:GitBranch,title:'Trazabilidad completa',text:'Registro histórico de lotes, labores y aplicaciones, siempre disponible y ordenado.'},{icon:PackageOpen,title:'Recursos optimizados',text:'Control de maquinarias, insumos, bodega y tiempos de trabajo desde un único lugar.'},{icon:BarChart3,title:'Decisiones estratégicas',text:'Dashboards que cruzan variables agronómicas y productivas para maximizar el rinde.'}];
const basics=['Cuaderno de campo digital','Control de cosechas','Gestión de bodega y stock básica','Registro de maquinarias','Reportes básicos de rinde'];
const premium=['Todo lo incluido en el Plan Básico','Costos, presupuestos y tesorería','Control de faenas y cosecha avanzada','Compras, proveedores y multialmacén','Órdenes de aplicación','Maquinarias y mantenimiento','Riego y sensores','Cuaderno de campo homologado','Módulo de ganadería','Dashboards y analítica predictiva'];
function Home(){return <div><SiteHeader/><main><section className="relative min-h-[calc(100vh-4.5rem)] overflow-hidden bg-surface-dark"><img src={fields} alt="Campos productivos del Norte Argentino" width={1600} height={900} className="absolute inset-0 h-full w-full object-cover opacity-65"/><div className="absolute inset-0 bg-gradient-to-r from-surface-dark via-surface-dark/80 to-transparent"/><div className="section-shell relative flex min-h-[calc(100vh-4.5rem)] items-center py-20"><div className="max-w-3xl animate-rise"><span className="inline-flex items-center gap-2 rounded-full border border-primary-foreground/25 bg-surface-dark/40 px-3.5 py-2 text-xs font-bold text-primary-foreground backdrop-blur"><Sparkles size={14} className="text-accent"/> Prueba gratis de 14 días para el Plan Básico</span><h1 className="mt-7 text-4xl font-bold leading-[1.08] text-primary-foreground sm:text-6xl lg:text-7xl">El campo produce datos.<br/><span className="text-accent">Sysagro los convierte</span><br/>en decisiones.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-primary-foreground/80 sm:text-lg">Gestión agropecuaria integral para conocer cada lote, optimizar recursos y anticipar el próximo paso de tu producción.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="bg-accent text-accent-foreground hover:bg-accent/90"><Link to="/demo">Probar demo <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><a href="#planes">Ver planes</a></Button></div><div className="mt-14 grid max-w-xl grid-cols-3 gap-6 border-t border-primary-foreground/20 pt-6 text-primary-foreground"><Stat n="1.240" l="hectáreas gestionadas"/><Stat n="99,8%" l="trazabilidad"/><Stat n="24/7" l="datos disponibles"/></div></div></div></section>
<section className="py-24"><div className="section-shell"><div className="max-w-2xl"><Eyebrow>Una plataforma, todo tu campo</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-5xl">Del lote al resultado, sin perder información en el camino.</h2><p className="mt-5 leading-7 text-muted-foreground">Sysagro es un sistema de gestión bajo modelo SaaS, diseñado para integrar la operación diaria con una visión estratégica del negocio.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{pillars.map((p,i)=><div key={p.title} className="panel group p-7 transition hover:-translate-y-1 hover:border-accent"><span className="grid size-12 place-items-center rounded-lg bg-primary text-primary-foreground"><p.icon/></span><span className="mt-8 block text-xs font-bold text-accent">0{i+1}</span><h3 className="mt-2 text-xl font-bold">{p.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.text}</p></div>)}</div></div></section>
<section className="bg-primary py-24 text-primary-foreground"><div className="section-shell grid gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><Eyebrow light>Institucional</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-5xl">Tecnología con raíces en el Norte Argentino.</h2><p className="mt-6 leading-7 text-primary-foreground/75">Nuestra misión es desarrollar soluciones especializadas que transformen datos de campo en información estratégica para optimizar rendimientos, garantizar la trazabilidad y promover un uso eficiente de los recursos.</p><p className="mt-5 border-l-2 border-accent pl-5 text-lg font-medium italic text-primary-foreground/90">“Ser el socio tecnológico de referencia para el agro del Norte Argentino.”</p></div><div className="grid gap-3 sm:grid-cols-2">{['Captación de primeros clientes','Lanzamiento del producto principal','Sostenibilidad económica','Expansión y optimización'].map((x,i)=><div key={x} className="rounded-lg border border-primary-foreground/15 bg-primary-foreground/5 p-5"><Target className="text-accent"/><p className="mt-6 text-xs text-primary-foreground/55">Objetivo 0{i+1}</p><h3 className="mt-1 font-bold">{x}</h3></div>)}</div></div></section><Org/>
<section id="planes" className="bg-secondary py-24"><div className="section-shell"><div className="mx-auto max-w-2xl text-center"><Eyebrow>Planes simples y transparentes</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-5xl">Una inversión que crece con tu campo.</h2><p className="mt-4 text-muted-foreground">Sin costos ocultos. Empezá hoy y comprobá el impacto en tu gestión.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-6 lg:grid-cols-2"><Price name="Básico" price="90" items={basics}/><Price name="Premium" price="170" items={premium} featured/></div></div></section>
<section className="py-20"><div className="section-shell"><div className="rounded-lg bg-surface-dark px-7 py-12 text-center text-primary-foreground sm:px-14"><Leaf className="mx-auto text-accent" size={34}/><h2 className="mt-5 text-3xl font-bold">Tu próxima campaña empieza con mejores datos.</h2><p className="mx-auto mt-3 max-w-xl text-primary-foreground/70">Recorré la demo y descubrí una forma más clara de gestionar tu operación.</p><Button asChild size="lg" className="mt-7 bg-accent text-accent-foreground hover:bg-accent/90"><Link to="/demo">Explorar Sysagro <ArrowRight/></Link></Button></div></div></section></main><Footer/></div>}
function Stat({n,l}:{n:string,l:string}){return <div><strong className="font-display text-xl">{n}</strong><span className="mt-1 block text-[10px] leading-4 text-primary-foreground/60">{l}</span></div>}
function Eyebrow({children,light=false}:{children:React.ReactNode,light?:boolean}){return <span className={`text-xs font-extrabold uppercase tracking-widest ${light?'text-accent':'text-primary'}`}>{children}</span>}
function Org(){const [active,setActive]=useState('Dirección General');const teams=[['Operaciones / Agronomía',Tractor],['Desarrollo de Software & QA',Database],['Comercial & Soporte',Users]] as const;return <section className="py-24"><div className="section-shell"><div className="text-center"><Eyebrow>Nuestro equipo</Eyebrow><h2 className="mt-3 text-3xl font-bold">Conocimiento agronómico y tecnológico</h2></div><div className="mx-auto mt-12 max-w-4xl text-center"><button onClick={()=>setActive('Dirección General')} className={`panel inline-flex items-center gap-3 px-6 py-4 font-bold ${active==='Dirección General'?'border-primary ring-2 ring-primary/15':''}`}><ShieldCheck className="text-primary"/>Dirección General<ChevronDown size={16}/></button><div className="mx-auto h-9 w-px bg-border"/><div className="grid gap-4 md:grid-cols-3">{teams.map(([t,I])=><button key={t} onClick={()=>setActive(t)} className={`panel flex min-h-28 flex-col items-center justify-center gap-3 p-5 font-semibold ${active===t?'border-primary bg-secondary ring-2 ring-primary/15':''}`}><I className="text-primary"/>{t}</button>)}</div><p className="mt-5 text-sm text-muted-foreground">Área seleccionada: <strong className="text-foreground">{active}</strong></p></div></div></section>}
function Price({name,price,items,featured=false}:{name:string,price:string,items:string[],featured?:boolean}){return <div className={`panel relative p-7 sm:p-9 ${featured?'border-primary bg-primary text-primary-foreground':''}`}>{featured&&<span className="absolute right-5 top-5 rounded-full bg-accent px-3 py-1 text-[10px] font-extrabold uppercase text-accent-foreground">Recomendado</span>}<p className={`text-sm font-bold ${featured?'text-accent':'text-primary'}`}>Plan {name}</p><div className="mt-3 flex items-end gap-1"><span className="font-display text-5xl font-bold">${price}</span><span className={featured?'text-primary-foreground/60':'text-muted-foreground'}>/ mes</span></div>{!featured&&<p className="mt-2 text-xs font-semibold text-primary">14 días gratis · sin tarjeta</p>}<ul className="mt-7 space-y-3">{items.map(x=><li key={x} className={`flex gap-3 text-sm ${featured?'text-primary-foreground/80':'text-muted-foreground'}`}><Check size={17} className="mt-0.5 shrink-0 text-accent"/>{x}</li>)}</ul><Button asChild size="lg" variant={featured?'secondary':'default'} className="mt-8 w-full"><Link to="/contacto" search={{plan:name.toLowerCase()}}>{featured?'Adquirir Plan Premium':'Iniciar prueba gratuita'}</Link></Button></div>}
function Footer(){return <footer className="border-t bg-card py-10"><div className="section-shell flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><Brand/><div className="text-sm text-muted-foreground"><a href="mailto:sysagro@gmail.com" className="hover:text-primary">sysagro@gmail.com</a><span className="mx-3">·</span>© 2026 Sysagro</div></div></footer>}
